const fs=require('fs'),path=require('path'),crypto=require('crypto');
const dir=__dirname;
const input=process.argv[2]||path.resolve(dir,'../../../builds/brutus-1_0_a0mk-kavi-balanced2.html');
const output=process.argv[3]||path.resolve(dir,'../../../builds/brutus-astra-s1-standalone.html');
const core=process.env.BOB_OW_MODULE||path.resolve(dir,'../../claude/overworld-2026-09-18/adventurers.js');
const baseline=fs.readFileSync(input,'utf8');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
if(hash(baseline)!=='0576e3fb2486affcf94959301b1e451e74c57ffa7937dceb5a6475d419287b8d')throw Error('Baseline hash mismatch');
const read=p=>fs.readFileSync(p,'utf8');
const result=require('./compose-s1.js')(baseline,{core:read(core),bridge:read(path.join(dir,'ow-bridge.js')),world:read(path.join(dir,'world-integration.js')),dungeon:read(path.join(dir,'dungeon-integration.js'))});
fs.writeFileSync(output,result);console.log(JSON.stringify({output,bytes:Buffer.byteLength(result),sha256:hash(result)}));
